### PR TITLE
Upgrade firebase/php-jwt to ^5.0

### LINKED ISSUE #79: Is it possible to upgrade firebase/php-jwt dependency to ^5.0 ?
Current composer dependency requirement for firebase/php-jwt is:

https://github.com/alphagov/notifications-php-client/blob/be0c5959f962afd8f0689ca5005d0ddaa05812fe/composer.json#L19

but I have a dependency in another library already being used in the same project to `firebase/php-jwt: ^5.0` — would an upgrade to ^5.0 break functionality in this project?

### PR DESCRIPTION
**Pull request by joesb**
## What problem does the pull request solve?

Upgrades firebase/php-jwt dependency library to ^5.0

Fixes #79 

## Checklist
- [x] I’ve used the pull request template
- [ ] I’ve written unit tests for these changes
- [ ] I’ve updated the documentation (in `DOCUMENTATION.md` and `CHANGELOG.md`)
- [ ] I’ve bumped the version number (`const VERSION` in `src/Client.php`)

### CODE REVIEW

**Comment by idavidmcdonald** [comment]
Thanks for opening this :) I'll create a new branch so we can run the tests against our CI system and check they pass.

I don't think we'd have any objections to bumping the version in principle but I'll do a quick bit of investigation to double check.

**Comment by idavidmcdonald** [comment]
See https://github.com/alphagov/notifications-php-client/pull/81 for tests

**Comment by idavidmcdonald** [comment]
Thanks again :) I'll let you know when this passes through our CI system and is released ready for use!

**Comment by joesb** [comment]
That's really great news. Thanks so much for looking at this. Much appreciated.

**Comment by idavidmcdonald** [comment]
All done, it's been deployed as version 3.0.1 and should be ready for you to use now. Thanks again!

**Pull request merged**
