### PR TITLE
Removed direct dependancy on php-http/httplug in favour of psr/http-c…

### PR DESCRIPTION
**Pull request by taylorsj1980**
…lient

## What problem does the pull request solve?
Removed the client's dependancy on the php-http/httplug package and allowed the Client class to use Psr\Http\Client\ClientInterface for HTTP clients instead of the deprecated Http\Client\HttpClient

## Checklist

- [x] I’ve used the pull request template
- [x] I’ve ~~written~~ updated unit tests for these changes
- [ ] I’ve updated the documentation (in `DOCUMENTATION.md` and `CHANGELOG.md`)
- [x] I’ve bumped the version number (`const VERSION` in `src/Client.php`) to 2.0.0

### CODE REVIEW

**Comment by quis** [comment]
@govuk-notify-jenkins test this please

**Comment by cooperaj** [comment]
Could you please let us know what the failure issue was? We don't have access to the Jenkins test instance.

**Comment by quis** [comment]
@cooperaj Hey, sorry about that. The failure was due to Jenkins not running `composer update` before running the tests. We’ll re-run the tests once we’ve updated Jenkins…

**Comment by leohemsted** [comment]
@govuk-notify-jenkins test this please

**Comment by leohemsted** [comment]
@govuk-notify-jenkins test this please

**Comment by leohemsted** [comment]
superceded by https://github.com/alphagov/notifications-php-client/pull/59

**Pull request closed without merging**
